run_on: &agents
  - Env=dev

steps:
  - label: "Run tests"
    command:
      - npm install
      - npm run lint
      - npm test
    artifact_paths:
      - "./build/**/*"
      - "./coverage/*"
    agents: *agents
    env:
      CI: 'true'

  - wait: ~
    branches: master

  - command:
    - npm install
    - npm publish
    label: Publish to npm
    branches: master
    agents: *agents
